# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: "echo ######################### From the root manager :)))"
  #
  #  
  config.vm.define "ansibleHost" do |ansibleHost|
  
    ansibleHost.vm.box = "ubuntu/bionic64"
	
	ansibleHost.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
	
	ansibleHost.disksize.size = '30GB'
	
	ansibleHost.ssh.password=false
	
	ansibleHost.ssh.insert_key=true
	
	ansibleHost.ssh.username="vagrant"
	
	# auto bridge, the same network with host, check your host ip list then assign a static ip without in the list. 
	# https://developer.hashicorp.com/vagrant/docs/networking/public_network
	# check list ip in host: arp -a
	ansibleHost.vm.network "public_network", ip: "192.168.1.10", use_dhcp_assigned_default_route: true
	
	ansibleHost.vm.synced_folder "C:/Users/Lenovo/OneDrive/Desktop/Techical/devops-tool-example/Ansible-Example/share-folder", "/home/share-folder"
	
	ansibleHost.vm.provision "shell" do |s| 
		s.inline = <<-SHELL
			echo "######################### this is ansible host controller manager"
			sudo apt update
			sudo apt install python3
			python3 --version
			python3 -m pip install --user ansible
			
			sudo apt update
			sudo apt install software-properties-common
			sudo add-apt-repository --yes --update ppa:ansible/ansible
			sudo apt install ansible
			
			ansible --version
			
			chmod+x /home/share-folder/scripts/ssh_script_client_config_ubuntu18.04.sh
			
			#config for the first slave
			/home/share-folder/scripts/ssh_script_client_config_ubuntu18.04.sh 192.168.1.11 vagrant /home/share-folder/ssh-keys/ ansible-key
			
			#config for the second slave
			/home/share-folder/scripts/ssh_script_client_config_ubuntu18.04.sh 192.168.1.12 root /home/share-folder/ssh-keys/ ansible-key
			
		SHELL
    end
	
	ansibleHost.vm.provider "virtualbox" do |vb|
	     vb.name = "ansible-host-ubuntu-bionic64-18.04"
		 vb.gui = false
		 vb.memory = "4096"
		 vb.cpus = 2
    end
   
  end
	
  #
  #
  config.vm.define "ansibleSlave" do |ansibleSlave|
  
    ansibleSlave.vm.box = "ubuntu/bionic64"
	
	ansibleSlave.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
	
	ansibleSlave.disksize.size = '30GB'
	
	ansibleSlave.ssh.password=false
	
	ansibleSlave.ssh.insert_key=true
	
	ansibleSlave.ssh.username="vagrant"
	
	ansibleSlave.vm.network "public_network", ip: "192.168.1.11", use_dhcp_assigned_default_route: true
	
	ansibleSlave.vm.synced_folder "C:/Users/Lenovo/OneDrive/Desktop/Techical/devops-tool-example/Ansible-Example/share-folder", "/home/share-folder"
	
	ansibleSlave.vm.provision "shell" do |s| 
		s.inline = <<-SHELL
			echo "######################### this is ansible slave manager"
			
			chmod+x /home/share-folder/scripts/ssh_script_server_config_ubuntu18.04.sh
			
			MY_NAME=$(whoami)
			
			file_path="/home/share-folder/ssh-keys/ansible-key.pub"
			# file_content="$(< $file_path)"
			file_content="$(cat $file_path)"
			echo "file key content: $file_content"
			
			/home/share-folder/scripts/ssh_script_server_config_ubuntu18.04.sh $MY_NAME "$file_content"
		SHELL
    end
	
	ansibleSlave.vm.provider "virtualbox" do |vb|
	     vb.name = "ansible-slave-ubuntu-bionic64-18.04"
		 vb.gui = false
		 vb.memory = "4096"
		 vb.cpus = 2
    end
	
  end
  
  #
  #
  config.vm.define "ansibleSlave1" do |ansibleSlave1|
  
    ansibleSlave1.vm.box = "ubuntu/bionic64"
	
	ansibleSlave1.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
	
	ansibleSlave1.disksize.size = '30GB'
	
	ansibleSlave1.ssh.password=false
	
	ansibleSlave1.ssh.insert_key=true
	
	ansibleSlave1.ssh.username="vagrant"
	
	ansibleSlave1.vm.network "public_network", ip: "192.168.1.12", use_dhcp_assigned_default_route: true
	
	ansibleSlave1.vm.synced_folder "C:/Users/Lenovo/OneDrive/Desktop/Techical/devops-tool-example/Ansible-Example/share-folder", "/home/share-folder"
	
	ansibleSlave1.vm.provision "shell" do |s| 
		s.inline = <<-SHELL
			echo "######################### this is ansible slave1 manager"
			
			chmod+x /home/share-folder/scripts/ssh_script_server_config_ubuntu18.04.sh
			
			MY_NAME=$(whoami)
			
			file_path="/home/share-folder/ssh-keys/ansible-key.pub"
			# file_content="$(< $file_path)"
			file_content="$(cat $file_path)"
			
			echo "file key content: $file_content"
			
			/home/share-folder/scripts/ssh_script_server_config_ubuntu18.04.sh $MY_NAME "$file_content"
			
		SHELL
    end
	
	ansibleSlave1.vm.provider "virtualbox" do |vb|
	     vb.name = "ansible-slave1-ubuntu-bionic64-18.04"
		 vb.gui = false
		 vb.memory = "4096"
		 vb.cpus = 2
    end
	
  end
	
end
