
---
- name: Install ansibleSlave1
  hosts: ansibleSlave1
  remote_user: vagrant
  
  become: yes  # Run tasks with sudo privileges
  vars:
  handlers:
   - name: Install docker
     import_tasks: task-docker.yml
     
   - name: Install microk8s
     import_tasks: task-microk8s.yml
   
  
- name: Install ansibleSlave
  hosts: ansibleSlave
  remote_user: vagrant
  
  handlers:
   - name: Install docker
     import_tasks: task-docker.yml
     
   - name: Install microk8s
     import_tasks: task-microk8s.yml