
---

- name: Check microk8s install or not
  ansible.builtin.shell: |
    which microk8s
  register: isMicrok8sInstall
  ignore_errors: true  # Continue even if the command fails
   
- name: Check MicroK8s is running or not
  ansible.builtin.command: microk8s status
  register: microk8sStatus
  ignore_errors: true
  when: isMicrok8sInstall is defined and isMicrok8sInstall.stdout.find('microk8s') != -1 # is contain string microk8s
  
- name: Stop microk8s if running
  ansible.builtin.systemd:
    name: microk8s
    state: stopped # "reloaded", "restarted", "started", "stopped"
  when: microk8sStatus is defined and microk8sStatus.stdout.find('microk8s') != -1
  ignore_errors: true
   
- name: Uninstall microk8s
  ansible.builtin.snap:
    name: microk8s
    state: absent
  when: isMicrok8sInstall is defined and isMicrok8sInstall.stdout.find('microk8s') != -1
  ignore_errors: true
   
# https://microk8s.io/docs/getting-started
- name: Install microk8s
  ansible.builtin.snap:
    name: microk8s
    state: present
    channel: 1.31
    classic: yes
  register: microk8sInstallStatus
  
 
- name: Join the groups
  ansible.builtin.shell: |
    sudo usermod -a -G microk8s $USER
    mkdir -p ~/.kube
    chmod 0700 ~/.kube
    su - $USER
    microk8s status --wait-ready
  ignore_errors: true
  
- name: Enable add-ons
  ansible.builtin.shell: |
    microk8s enable dns
    microk8s enable hostpath-storage
    microk8s enable dashboard registry storage ingress
  ignore_errors: true   
  
- name: Setup 
  ansible.builtin.shell: |
    sudo ufw allow in on cni0 && sudo ufw allow out on cni0
    sudo ufw default allow routed
    
    ipRange="10.1.1.9-10.250.250.250"
    echo "$ipRange" | sudo microk8s enable metallb
    unset ipRange;
    
    if [ -f ~/.bash_aliases ] && ! sudo grep -q "microk8s kubectl" ~/.bash_aliases; then 
        echo "alias kubectl='microk8s kubectl'" | sudo tee -a ~/.bash_aliases
    fi
    sleep 10
    
    sudo microk8s kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml
    
    token=$(sudo microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
    sudo microk8s kubectl -n kube-system describe secret $token
    sleep 30
  ignore_errors: true 
  register: microk8sSetupStatus  
  
- name: Enable the Microk8s service
  ansible.builtin.systemd:
    name: microk8s
    enabled: yes
  ignore_errors: true
  register: microk8sEnableStatus 

- name: Start the Microk8s service
  ansible.builtin.systemd:
    name: microk8s
    state: started
  ignore_errors: true
  register: microk8sStartStatus
  
- name: Show installation result
  ansible.builtin.debug:
    msg: 
        - "Microk8s installation result: {{ microk8sInstallStatus }}"
        - "Microk8s setup result: {{ microk8sSetupStatus }}"
        - "Microk8s Enable result: {{ microk8sEnableStatus }}"
        - "Microk8s Start result: {{ microk8sStartStatus }}"