
---


- name: Check docker install or not
  ansible.builtin.shell: |
    which docker
  register: isDockerInstall
  ignore_errors: true  # Continue even if the command fails

# 'https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module'
- name: Uninstall old Docker
  ansible.builtin.shell: |
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
  delegate_to: localhost
 
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository     
- name: Set up Docker apt repository
  ansible.builtin.shell: |
    sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
  args:
     warn: true  # Suppress warnings for this task
     
# using shell that not work as expect, the screen not show anything for hours
#- name: Install Docker
#  ansible.builtin.shell: |
#    echo "install docker"
#    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#    sudo docker run hello-world
#  debugger: always   
  
- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    #fail_on_autoremove: yes
    #install_recommends: no
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
#  debugger: always 
    
- name: Enable the Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    
- name: Start the Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
#or
#- name: Start Docker service
#  service:
#    name: docker
#    state: started
#    enabled: yes
#    